### PR TITLE
A bunch of refactoring to enable additional functionality

### PR DESCRIPTION
**Pull request by jt000**
This unused dependency is causing an issue when run w/ ui.router.

Fixes issue #14

### CODE REVIEW

**Comment by jt000** [comment]
Merged in additional functionality to include:
- Adding build using GruntJS
- Adding minification
- Allowing access to full application insights object
- Adding stub for easy testing when window.appInsights not available
- Allowing appId to be optionally set in AppInsights prescribed way (during script initialization). This also enables additional config options to be set w/o having to go through start()

**Comment by johnhidey** [comment]
@jt000 sorry I haven't had much time lately to work on this, or even review pull requests coming it.  Appreciate all your changes and things are looking good.  You think you could also update the README so everyone will be aware of the changes and how to use them?  Update the pull-request with that and I'll merge this in

**Comment by johnhidey** [comment]
@jt000 I went ahead and merged in your request.  I spoke too soon before noticing that README didn't really need updating.  I also updated the CHANGELOG and give credit where the credit was due.

**Comment by jt000** [comment]
Thanks! The readme doesn't need updating since I didn't break back-compat, but I could probably add some more details showing the additional functionality. I'll try and take care of that this week & submit another PR.

**Pull request merged**
